apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-metrics
  namespace: skillio
  labels:
    app: user
spec:
  selector:
    matchLabels:
      app: user
  namespaceSelector:
    matchNames:
      - skillio
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
