apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription
  namespace: {{ .Values.namespace }}
  labels:
    app: subscription
spec:
  replicas: {{ .Values.replicas.subscription }}
  selector:
    matchLabels:
      app: subscription
  template:
    metadata:
      labels:
        app: subscription
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: subscription
          image: "{{ .Values.images.subscription.repository }}:{{ .Values.images.subscription.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.subscription.containerPort }}
          env:
            - name: SERVER_PORT
              value: "{{ .Values.subscription.containerPort }}"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.subscription.databaseUrl | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
