apiVersion: v1
kind: Service
metadata:
  name: training
  namespace: skillio
  labels:
    app: training
spec:
  selector:
    app: training
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8086
      nodePort: 30080
