apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription
  namespace: skillio
  labels:
    app: subscription
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription
  template:
    metadata:
      labels:
        app: subscription
    spec:
      containers:
        - name: subscription
          image: wissemsbaiti/skillio-subscription:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql.skillio.svc.cluster.local:3306/entreprise_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
