apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription
  labels:
    app: subscription
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription
  template:
    metadata:
      labels:
        app: subscription
    spec:
      containers:
        - name: subscription
          image: wissemsbaiti/skillio-subscription:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"

