apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: subscription-metrics
  namespace: skillio
  labels:
    app: subscription
spec:
  selector:
    matchLabels:
      app: subscription
  namespaceSelector:
    matchNames:
      - skillio
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
