apiVersion: v1
kind: Service
metadata:
  name: subscription
  namespace: skillio
  labels:
    app: subscription
spec:
  selector:
    app: subscription
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30084
