apiVersion: apps/v1
kind: Deployment
metadata:
  name: event
  labels:
    app: event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event
  template:
    metadata:
      labels:
        app: event
    spec:
      containers:
        - name: event
          image: wissemsbaiti/skillio-event:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"

