frontend:
  image: 192.168.33.10:8888/skillio/skillio-frontend:latest
apiGateway:
  image: 192.168.33.10:8888/skillio/skillio-api-gateway:latest
user:
  image: 192.168.33.10:8888/skillio/skillio-user:latest
entreprise:
  image: 192.168.33.10:8888/skillio/skillio-entreprise:latest
event:
  image: 192.168.33.10:8888/skillio/skillio-event:latest
subscription:
  image: 192.168.33.10:8888/skillio/skillio-subscription:latest
training:
  image: 192.168.33.10:8888/skillio/skillio-training:latest
