apiVersion: apps/v1
kind: Deployment
metadata:
  name: event
  namespace: skillio
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: event
  template:
    metadata:
      labels:
        app: event
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: event
          image: {{ .Values.event.image }}
          ports:
            - containerPort: 80

          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/entreprise_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://localhost:8762/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: event
  namespace: skillio
spec:
  type: NodePort
  selector:
    app: event
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30083
