apiVersion: apps/v1
kind: Deployment
metadata:
  name: entreprise
  namespace: skillio
  labels:
    app: entreprise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entreprise
  template:
    metadata:
      labels:
        app: entreprise
    spec:
      containers:
        - name: entreprise
          image: wissemsbaiti/skillio-entreprise:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: SERVER_PORT
              value: "8083"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql.skillio.svc.cluster.local:3306/entreprise_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
