apiVersion: v1
kind: Service
metadata:
  name: entreprise
  namespace: skillio
  labels:
    app: entreprise
spec:
  selector:
    app: entreprise
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8083
      nodePort: 30082
