spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://192.168.33.10:30095"
              - "http://localhost:4200"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
      default-filters:
        - RemoveResponseHeader=Access-Control-Allow-Origin
        - RemoveResponseHeader=Access-Control-Allow-Credentials
        - RemoveResponseHeader=Access-Control-Expose-Headers
        - RemoveResponseHeader=Access-Control-Allow-Headers
        - RemoveResponseHeader=Access-Control-Max-Age
        - "DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Allow-Headers Access-Control-Expose-Headers Access-Control-Max-Age"
